name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Tox
        run: pip install tox
      - name: Lint
        run: tox -e flake8
      - name: Test and Build Wheel
        run: tox
